[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'npx prisma migrate deploy && node prisma/seed.js && node dist/main'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
