[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'npx prisma db push --force-reset --accept-data-loss && node prisma/seed.js && node dist/main'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
